### ISSUE TITLE
Throttle and Brake Gauges

### ISSUE THREAD

**Issue by photon1503** [andreasdahl1987/DahlDesignDash#11]
Hi @andreasdahl1987 and @mcowger ,

before I create a pull request... what do you think about a Breake/Gear gauge?

I created a widget which could easily be shown or hidden with a dedicated setting. (Hint - you need to press the Play button in the GIF below to see it in action)

![Animation](https://user-images.githubusercontent.com/14548927/200138219-53ab0bbc-d8a7-4df8-ad1d-372e873555b4.gif)

**Comment by andreasdahl1987** [comment]
I think this is really cool :D 

It looks like the gauge is about 1 pixel too tall? And the throttle gauge too wide?

The dash already have a throttle/brake gauge, but it is hidden for almost all cars. Only visible for RX cars, which have no use for the pitmenu or the incar menu.

![image](https://user-images.githubusercontent.com/40788634/200138817-460263e0-0519-4805-a278-0b540ba82e3e.png)

I was discussing with @mcowger about having the option to force a type of display at the bottom bar: 
- Automatic selection
- Pit menu only
- Pit + InCar
- Brake/Throttle

But your design has a different use, and I think you could add it with an option to turn on/off and default off. 

We're getting a lot of new features now, and a bunch of options for customization. I think the next in line would be to organize the plugin menu a little more.

**Comment by mcowger** [comment]
I'm in favor of this design, as a replacement for the one that shows up in the RX cars.

**Comment by mcowger** [comment]
I am working on a reinagination of the settings panel a bit, but will take a while to get through it.

**Comment by photon1503** [comment]
I didn't get that there is already a gauge available :-)

Yes it was a little bit too tall - fixed that.

**Comment by andreasdahl1987** [comment]
> I'm in favor of this design, as a replacement for the one that shows up in the RX cars.

Any suggestions on what to have there instead? The RX cars have pretty much zero use of the menus, except the stop watch, which again is fairly useless. Im using the stop watch a lot for mapping out cars, but Im not sure anyone else is 😂 Maybe some info on car ahead/behind?

**Comment by andreasdahl1987** [comment]
> I am working on a reinagination of the settings panel a bit, but will take a while to get through it.

Epic.

**Comment by andreasdahl1987** [comment]
> I didn't get that there is already a gauge available :-)
> 
> Yes it was a little bit too tall - fixed that.

PR lets go!

**Comment by mcowger** [comment]
> > I'm in favor of this design, as a replacement for the one that shows up in the RX cars.
> 
> 
> 
> Any suggestions on what to have there instead? The RX cars have pretty much zero use of the menus, except the stop watch, which again is fairly useless. Im using the stop watch a lot for mapping out cars, but Im not sure anyone else is 😂 Maybe some info on car ahead/behind?

I think it's ok to just show nothing when the data aren't relevant

**Comment by andreasdahl1987** [comment]
@mcowger @photon1503 considering a joker lap completion graphic, that way the RX page on right side infobox os freed up for opponent deøta changes, which is comming
