### ISSUE TITLE
Delta times inaccurate or frozen

### ISSUE THREAD

**Issue by robrodriguezjr** [andreasdahl1987/DahlDesignDash#14]
I am having a particular issue with the delta display. It seems to work for a few laps then suddenly stops working. It will either will show a large delta amount that is not correct, or become inaccurate until a new lap begins, or simply will stay stuck on 0…no changing of the displays will get it to work again. Only restarting the session/race, etc.

It happens whether I’m using a Vocore or a tablet. Everything else seems to work fine.
[LapLog.txt](https://github.com/andreasdahl1987/DahlDesignDash/files/10043720/LapLog.txt)

**Comment by andreasdahl1987** [comment]
@robrodriguezjr Thanks for posting this, I'll have a look! Can you please provide the SimHub.log file as well? SimHub makes one on each startup, "SimHub.log" is the most recent, then "SimHub.log.1", "SimHub.log.2" etc. Find the one that matches the time of this issue, timestamps for each logged line in the document.

**Comment by andreasdahl1987** [comment]
Closed after discussing with @robrodriguezjr. The issue was not with the dashboard or plugin.
